version: '3.3'
services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'flatten-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Europe/Berlin'
    ports:
      - 3306:3306
    volumes:
      - flatten_db_volume:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  flatten_db_volume: